CREATE TABLE `MEMBER` (
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`MEMBER_PASSWORD`	VARCHAR2(20)	NOT NULL,
	`MEMBER_NAME`	VARCHAR2(20)	NOT NULL,
	`MEMBER_EMAIL`	VARCHAR2(50)	NOT NULL,
	`MEMBER_PHONE`	VARCHAR2(20)	NOT NULL,
	`MEMBER_ADDRESS`	VARCHAR2(200)	NOT NULL	COMMENT '67자 미만',
	`MEMBER_GENDER`	CHAR(1)	NOT NULL	COMMENT '"M", "F"',
	`MEMBER_BIRTHOFDATE`	DATE	NOT NULL
);

CREATE TABLE `EV_ITEM` (
	`E_ITEMNO`	VARCHAR2(20)	NOT NULL,
	`E_ITEMNAME`	VARCHAR2(20)	NOT NULL
);

CREATE TABLE `PRODUCT` (
	`P_ID`	VARCHAR2(20)	NOT NULL,
	`P_NAME`	VARCHAR2(100)	NOT NULL	COMMENT '34자 미만',
	`P_CATEGORY`	NUMBER	NOT NULL	COMMENT '1. 한식, 2.중식, 3.일식, 4.양식, 5.동남아, 6.기타',
	`P_PRICE`	NUMBER	NOT NULL,
	`P_SELLAMOUNT`	NUMBER	NOT NULL,
	`P_WEIGHT`	NUMBER	NULL,
	`P_CALORIE`	NUMBER	NULL,
	`P_FLAVOR`	VARCHAR2(20)	NULL,
	`P_POSTDATE`	TIMESTAMP	NOT NULL,
	`P_SALECHECK`	CHAR(1)	NOT NULL	COMMENT '"Y", "N"',
	`P_DETAIL`	VARCHAR2(900)	NOT NULL
);

CREATE TABLE `NT_PLATING_CONTENT` (
	`B_NO`	NUMBER	NOT NULL,
	`B_CONCEPT`	NUMBER	NOT NULL	COMMENT '1.생일 2.캠핑 3. 홈파티 4.안주',
	`B_TITLE`	VARCHAR2(60)	NOT NULL	COMMENT '20자미만',
	`B_CONTENT`	VARCHAR2(900)	NOT NULL	COMMENT '300자미만',
	`B_DATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL
);

CREATE TABLE `NT_PLATING_RECOMMENT` (
	`R_NO`	NUMBER	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`R_CONTENT`	VARCHAR2(300)	NOT NULL	COMMENT '100자미만',
	`R_DATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`B_NO`	NUMBER	NOT NULL
);

CREATE TABLE `NT_RECIPE_CONTENT` (
	`B_NO`	NUMBER	NOT NULL,
	`B_CONCEPT`	NUMBER	NOT NULL	COMMENT '1.한식 2.중식 3.일식 4.양식',
	`B_TITLE`	VARCHAR2(60)	NOT NULL	COMMENT '20자미만',
	`B_CONTENT`	VARCHAR2(900)	NOT NULL	COMMENT '300자미만',
	`B_DATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL
);

CREATE TABLE `NT_RECIPE_IMG` (
	`I_NO`	NUMBER	NOT NULL,
	`B_NO`	NUMBER	NOT NULL	COMMENT '최대5개까지',
	`I_FILE`	VARCHAR2(300)	NOT NULL
);

CREATE TABLE `NT_RECIPE_RECOMMENT` (
	`R_NO`	NUMBER	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`R_CONTENT`	VARCHAR2(300)	NOT NULL	COMMENT '100자미만',
	`R_DATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`B_NO`	NUMBER	NOT NULL
);

CREATE TABLE `NT_CONTEST_CONTENT` (
	`B_NO`	NUMBER	NOT NULL,
	`B_TITLE`	VARCHAR2(60)	NOT NULL	COMMENT '20자미만',
	`B_CONTENT`	VARCHAR2(900)	NOT NULL	COMMENT '300자미만',
	`B_DATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL
);

CREATE TABLE `NT_CONTEST_IMG` (
	`I_NO`	NUMBER	NOT NULL,
	`B_NO`	NUMBER	NOT NULL	COMMENT '최대5개까지',
	`I_FILE`	VARCHAR2(300)	NOT NULL
);

CREATE TABLE `NT_CONTEST_RECOMMENT` (
	`R_NO`	NUMBER	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`R_CONTENT`	VARCHAR2(300)	NOT NULL	COMMENT '100자미만',
	`R_DATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`B_NO`	NUMBER	NOT NULL
);

CREATE TABLE `CR_RECIPE_RECOMMENT` (
	`CRRERECOMMENT_NO`	NUMBER	NOT NULL,
	`CRRERECOMMENT_POSTDATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`CRRERECOMMENT_CONTENT`	varchar2(300)	NOT NULL	COMMENT '100자 미만',
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`CRRECONTENT_NO`	NEMBER	NOT NULL
);

CREATE TABLE `ORDER` (
	`ORDER_NUMBER`	VARCHAR2(20)	NOT NULL,
	`ORDER_CONTACT`	NUMBER	NOT NULL,
	`ORDER_REQUEST`	VARCHAR2(150)	NOT NULL	COMMENT '51자 미만',
	`ORDER_DATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`ORDER_STATUS`	VARCHAR2(30)	NULL,
	`ORDER_PAYMENT`	VARCHAR2(30)	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`ORDER_DELIVERY`	VARCHAR2(100)	NOT NULL
);

CREATE TABLE `NT_CONTEST_LIKE` (
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`B_NO`	NUMBER	NOT NULL
);

CREATE TABLE `NT_PLATING_IMG` (
	`I_NO`	NUMBER	NOT NULL,
	`B_NO`	NUMBER	NOT NULL	COMMENT '최대5개까지',
	`I_FILE`	VARCHAR2(300)	NOT NULL
);

CREATE TABLE `EV_CONTENT` (
	`E_NO`	NUMBER	NOT NULL,
	`E_ITEMNO`	VARCHAR2(20)	NOT NULL,
	`E_POSTDATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`E_TITLE`	VARCHAR2(60)	NOT NULL	COMMENT '20자 미만',
	`E_CONTENT`	VARCHAR2(900)	NOT NULL	COMMENT '300자 미만',
	`E_STARTDATE`	DATE	NOT NULL,
	`E_ENDDATE`	DATE	NOT NULL
);

CREATE TABLE `EV_ITEM_MEMBER` (
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`E_ITEMNO`	VARCHAR2(20)	NULL
);

CREATE TABLE `CR_RECIPE_CONTENT` (
	`CRRECONTENT_NO`	NEMBER	NOT NULL,
	`CRRECONTENT_POSTDATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`CRRECONTENT_TITLE`	VARCHAR2(60)	NOT NULL	COMMENT '20자 미만',
	`CRRECONTENT_CONTENT`	VARCHAR2(900)	NOT NULL	COMMENT '300자 미만'
);

CREATE TABLE `CR_RECIPE_CONTENT_LIKE` (
	`CRRECONTENT_NO`	NUMBER	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL
);

CREATE TABLE `QNA` (
	`QNA_NO`	NUMBER	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`QNA_POSTDATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`QNA_TITLE`	VARCHAR2(60)	NOT NULL	COMMENT '20자 미만',
	`QNA_CONTENT`	VARCHAR2(900)	NOT NULL	COMMENT '300자 미만'
);

CREATE TABLE `COMMONQNA` (
	`COMMONQNA_NO`	NUMBER	NOT NULL,
	`COMMONQNA_POSTDATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`COMMONQNA_TITLE`	VARCHAR2(60)	NOT NULL	COMMENT '20자 미만',
	`COMMONQNA__CONTENT`	VARCHAR2(900)	NOT NULL	COMMENT '300자 미만'
);

CREATE TABLE `NOTICE` (
	`NOTICE_NO`	NUMBER	NOT NULL,
	`NOTICE_POSTDATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`NOTICE_TITLE`	VARCHAR2(60)	NOT NULL	COMMENT '20자 미만',
	`NOTICE_CONTENT`	VARCHAR2(900)	NOT NULL	COMMENT '300자 미만'
);

CREATE TABLE `QNA_RECOMMENT` (
	`QNARECOMMENT_NO`	NUMBER	NOT NULL,
	`QNA_NO`	NUMBER	NOT NULL,
	`QNARECOMMENT_POSTDATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`QNARECOMMENT_CONTENT`	VARCHAR2(300)	NOT NULL	COMMENT '100자 미만'
);

CREATE TABLE `PRODUCT_REVIEW` (
	`PRODUCTREVIEW_NO`	NUMBER	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`PRODUCTREVIEW_POSTDATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`PRODUCTREVIEW_CONTENT`	VARCHAR2(300)	NOT NULL	COMMENT '100자 미만'
);

CREATE TABLE `PRODUCT_REVIEW_IMAGE` (
	`PRODUCTREVIEW_IMAGENO`	NUMBER	NOT NULL,
	`PRODUCTREVIEW_NO`	NUMBER	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`PRODUCTREVIEW_IMAGEPOSITION`	VARCHAR2(300)	NOT NULL
);

CREATE TABLE `BASKET_ITEM` (
	`P_ID`	VARCHAR2(20)	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`BASKETITEM_AMOUNT`	NUMBER	NOT NULL
);

CREATE TABLE `ORDERED_PRODUCT` (
	`P_ID`	VARCHAR2(20)	NOT NULL,
	`ORDER_NUMBER`	VARCHAR2(20)	NOT NULL,
	`ORDEREDPRODUCT_AMOUNT`	NUMBER	NOT NULL
);

CREATE TABLE `NT_PLATING_LIKE` (
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`B_NO`	NUMBER	NOT NULL
);

CREATE TABLE `NT_RECIPE_LIKE` (
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`B_NO`	NUMBER	NOT NULL
);

CREATE TABLE `CR_RECIPE_CONTENT_IMAGE` (
	`CRRECIPECOTENTIMAGE_NO`	NUMBER	NOT NULL,
	`CRRECONTENT_NO`	NEMBER	NOT NULL,
	`CRRECONTENTIMAGE_LOCATION`	VARCHAR2(300)	NOT NULL
);

CREATE TABLE `MBTI` (
	`MBTI_TYPE`	VARCHAR2(100)	NOT NULL,
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL
);

CREATE TABLE `DELIVERY` (
	`ORDER_NUMBER`	VARCHAR2(20)	NOT NULL,
	`D_DATE`	DATE	NOT NULL,
	`D_COMPANY`	VARCHAR2(100)	NOT NULL,
	`D_NUMBER`	NUMBER	NOT NULL,
	`D_STATUS`	CHAR(3)	NOT NULL	COMMENT '"1 - 발송", "2 - 배송 중", "3- 배송 완료"',
	`D_TYPE`	VARCHAR2(50)	NOT NULL
);

CREATE TABLE `CopyOfPAYMENT` (
	`PAY_NUMBER`	NUMBER	NOT NULL,
	`ORDER_NUMBER`	VARCHAR2(20)	NOT NULL,
	`APY_NAME`	VARCHAR2(50)	NOT NULL,
	`PAY_DATE`	TIMESTAMP	NOT NULL	DEFAULT SYSTIMESTAMP,
	`PAY_TOTAL`	NUMBER	NOT NULL,
	`PAY_METHOD`	NUMBER	NOT NULL	COMMENT '1. 카드 2. 무통장입금 3. 실시간계좌이체',
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL
);

CREATE TABLE `DETAIL_IMAGE` (
	`P_ID`	VARCHAR2(20)	NOT NULL,
	`Field`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `MEMBERAGREEMENT` (
	`MA_ID`	VARCHAR2(20)	NOT NULL,
	`MA_CONTENT`	VARCHAR2(900)	NOT NULL,
	`MA_APPLYDATE`	TIMESTAMP	NOT NULL,
	`MA_POSTDATE`	TIMESTAMP	NOT NULL,
	`MA_REQUIRED`	CHAR(1)	NOT NULL	COMMENT '"Y", "N"'
);

CREATE TABLE `AGREEMENT_HISTORY` (
	`MEMBER_ID`	VARCHAR2(20)	NOT NULL,
	`MA_ID`	VARCHAR2(20)	NOT NULL,
	`AH_AGREE`	CHAR(1)	NOT NULL	COMMENT '"Y", "N"',
	`AH_AGREEDATE`	TIMESTAMP	NOT NULL
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`MEMBER_ID`
);

ALTER TABLE `EV_ITEM` ADD CONSTRAINT `PK_EV_ITEM` PRIMARY KEY (
	`E_ITEMNO`
);

ALTER TABLE `PRODUCT` ADD CONSTRAINT `PK_PRODUCT` PRIMARY KEY (
	`P_ID`
);

ALTER TABLE `NT_PLATING_CONTENT` ADD CONSTRAINT `PK_NT_PLATING_CONTENT` PRIMARY KEY (
	`B_NO`
);

ALTER TABLE `NT_PLATING_RECOMMENT` ADD CONSTRAINT `PK_NT_PLATING_RECOMMENT` PRIMARY KEY (
	`R_NO`,
	`MEMBER_ID`
);

ALTER TABLE `NT_RECIPE_CONTENT` ADD CONSTRAINT `PK_NT_RECIPE_CONTENT` PRIMARY KEY (
	`B_NO`
);

ALTER TABLE `NT_RECIPE_IMG` ADD CONSTRAINT `PK_NT_RECIPE_IMG` PRIMARY KEY (
	`I_NO`,
	`B_NO`
);

ALTER TABLE `NT_RECIPE_RECOMMENT` ADD CONSTRAINT `PK_NT_RECIPE_RECOMMENT` PRIMARY KEY (
	`R_NO`,
	`MEMBER_ID`
);

ALTER TABLE `NT_CONTEST_CONTENT` ADD CONSTRAINT `PK_NT_CONTEST_CONTENT` PRIMARY KEY (
	`B_NO`
);

ALTER TABLE `NT_CONTEST_IMG` ADD CONSTRAINT `PK_NT_CONTEST_IMG` PRIMARY KEY (
	`I_NO`,
	`B_NO`
);

ALTER TABLE `NT_CONTEST_RECOMMENT` ADD CONSTRAINT `PK_NT_CONTEST_RECOMMENT` PRIMARY KEY (
	`R_NO`,
	`MEMBER_ID`
);

ALTER TABLE `CR_RECIPE_RECOMMENT` ADD CONSTRAINT `PK_CR_RECIPE_RECOMMENT` PRIMARY KEY (
	`CRRERECOMMENT_NO`
);

ALTER TABLE `ORDER` ADD CONSTRAINT `PK_ORDER` PRIMARY KEY (
	`ORDER_NUMBER`
);

ALTER TABLE `NT_CONTEST_LIKE` ADD CONSTRAINT `PK_NT_CONTEST_LIKE` PRIMARY KEY (
	`MEMBER_ID`,
	`B_NO`
);

ALTER TABLE `NT_PLATING_IMG` ADD CONSTRAINT `PK_NT_PLATING_IMG` PRIMARY KEY (
	`I_NO`,
	`B_NO`
);

ALTER TABLE `EV_CONTENT` ADD CONSTRAINT `PK_EV_CONTENT` PRIMARY KEY (
	`E_NO`,
	`E_ITEMNO`
);

ALTER TABLE `EV_ITEM_MEMBER` ADD CONSTRAINT `PK_EV_ITEM_MEMBER` PRIMARY KEY (
	`MEMBER_ID`
);

ALTER TABLE `CR_RECIPE_CONTENT` ADD CONSTRAINT `PK_CR_RECIPE_CONTENT` PRIMARY KEY (
	`CRRECONTENT_NO`
);

ALTER TABLE `CR_RECIPE_CONTENT_LIKE` ADD CONSTRAINT `PK_CR_RECIPE_CONTENT_LIKE` PRIMARY KEY (
	`CRRECONTENT_NO`,
	`MEMBER_ID`
);

ALTER TABLE `QNA` ADD CONSTRAINT `PK_QNA` PRIMARY KEY (
	`QNA_NO`,
	`MEMBER_ID`
);

ALTER TABLE `COMMONQNA` ADD CONSTRAINT `PK_COMMONQNA` PRIMARY KEY (
	`COMMONQNA_NO`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`NOTICE_NO`
);

ALTER TABLE `QNA_RECOMMENT` ADD CONSTRAINT `PK_QNA_RECOMMENT` PRIMARY KEY (
	`QNARECOMMENT_NO`,
	`QNA_NO`
);

ALTER TABLE `PRODUCT_REVIEW` ADD CONSTRAINT `PK_PRODUCT_REVIEW` PRIMARY KEY (
	`PRODUCTREVIEW_NO`,
	`MEMBER_ID`
);

ALTER TABLE `PRODUCT_REVIEW_IMAGE` ADD CONSTRAINT `PK_PRODUCT_REVIEW_IMAGE` PRIMARY KEY (
	`PRODUCTREVIEW_IMAGENO`,
	`PRODUCTREVIEW_NO`,
	`MEMBER_ID`
);

ALTER TABLE `BASKET_ITEM` ADD CONSTRAINT `PK_BASKET_ITEM` PRIMARY KEY (
	`P_ID`,
	`MEMBER_ID`
);

ALTER TABLE `NT_PLATING_LIKE` ADD CONSTRAINT `PK_NT_PLATING_LIKE` PRIMARY KEY (
	`MEMBER_ID`,
	`B_NO`
);

ALTER TABLE `NT_RECIPE_LIKE` ADD CONSTRAINT `PK_NT_RECIPE_LIKE` PRIMARY KEY (
	`MEMBER_ID`,
	`B_NO`
);

ALTER TABLE `CR_RECIPE_CONTENT_IMAGE` ADD CONSTRAINT `PK_CR_RECIPE_CONTENT_IMAGE` PRIMARY KEY (
	`CRRECIPECOTENTIMAGE_NO`,
	`CRRECONTENT_NO`
);

ALTER TABLE `MBTI` ADD CONSTRAINT `PK_MBTI` PRIMARY KEY (
	`MBTI_TYPE`,
	`MEMBER_ID`
);

ALTER TABLE `DELIVERY` ADD CONSTRAINT `PK_DELIVERY` PRIMARY KEY (
	`ORDER_NUMBER`
);

ALTER TABLE `CopyOfPAYMENT` ADD CONSTRAINT `PK_COPYOFPAYMENT` PRIMARY KEY (
	`PAY_NUMBER`,
	`ORDER_NUMBER`
);

ALTER TABLE `MEMBERAGREEMENT` ADD CONSTRAINT `PK_MEMBERAGREEMENT` PRIMARY KEY (
	`MA_ID`
);

ALTER TABLE `AGREEMENT_HISTORY` ADD CONSTRAINT `PK_AGREEMENT_HISTORY` PRIMARY KEY (
	`MEMBER_ID`,
	`MA_ID`
);

ALTER TABLE `NT_PLATING_RECOMMENT` ADD CONSTRAINT `FK_MEMBER_TO_NT_PLATING_RECOMMENT_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `NT_RECIPE_IMG` ADD CONSTRAINT `FK_NT_RECIPE_CONTENT_TO_NT_RECIPE_IMG_1` FOREIGN KEY (
	`B_NO`
)
REFERENCES `NT_RECIPE_CONTENT` (
	`B_NO`
);

ALTER TABLE `NT_RECIPE_RECOMMENT` ADD CONSTRAINT `FK_MEMBER_TO_NT_RECIPE_RECOMMENT_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `NT_CONTEST_IMG` ADD CONSTRAINT `FK_NT_CONTEST_CONTENT_TO_NT_CONTEST_IMG_1` FOREIGN KEY (
	`B_NO`
)
REFERENCES `NT_CONTEST_CONTENT` (
	`B_NO`
);

ALTER TABLE `NT_CONTEST_RECOMMENT` ADD CONSTRAINT `FK_MEMBER_TO_NT_CONTEST_RECOMMENT_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `NT_CONTEST_LIKE` ADD CONSTRAINT `FK_MEMBER_TO_NT_CONTEST_LIKE_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `NT_CONTEST_LIKE` ADD CONSTRAINT `FK_NT_CONTEST_CONTENT_TO_NT_CONTEST_LIKE_1` FOREIGN KEY (
	`B_NO`
)
REFERENCES `NT_CONTEST_CONTENT` (
	`B_NO`
);

ALTER TABLE `NT_PLATING_IMG` ADD CONSTRAINT `FK_NT_PLATING_CONTENT_TO_NT_PLATING_IMG_1` FOREIGN KEY (
	`B_NO`
)
REFERENCES `NT_PLATING_CONTENT` (
	`B_NO`
);

ALTER TABLE `EV_CONTENT` ADD CONSTRAINT `FK_EV_ITEM_TO_EV_CONTENT_1` FOREIGN KEY (
	`E_ITEMNO`
)
REFERENCES `EV_ITEM` (
	`E_ITEMNO`
);

ALTER TABLE `EV_ITEM_MEMBER` ADD CONSTRAINT `FK_MEMBER_TO_EV_ITEM_MEMBER_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `CR_RECIPE_CONTENT_LIKE` ADD CONSTRAINT `FK_CR_RECIPE_CONTENT_TO_CR_RECIPE_CONTENT_LIKE_1` FOREIGN KEY (
	`CRRECONTENT_NO`
)
REFERENCES `CR_RECIPE_CONTENT` (
	`CRRECONTENT_NO`
);

ALTER TABLE `CR_RECIPE_CONTENT_LIKE` ADD CONSTRAINT `FK_MEMBER_TO_CR_RECIPE_CONTENT_LIKE_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `QNA` ADD CONSTRAINT `FK_MEMBER_TO_QNA_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `QNA_RECOMMENT` ADD CONSTRAINT `FK_QNA_TO_QNA_RECOMMENT_1` FOREIGN KEY (
	`QNA_NO`
)
REFERENCES `QNA` (
	`QNA_NO`
);

ALTER TABLE `PRODUCT_REVIEW` ADD CONSTRAINT `FK_MEMBER_TO_PRODUCT_REVIEW_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `PRODUCT_REVIEW_IMAGE` ADD CONSTRAINT `FK_PRODUCT_REVIEW_TO_PRODUCT_REVIEW_IMAGE_1` FOREIGN KEY (
	`PRODUCTREVIEW_NO`
)
REFERENCES `PRODUCT_REVIEW` (
	`PRODUCTREVIEW_NO`
);

ALTER TABLE `PRODUCT_REVIEW_IMAGE` ADD CONSTRAINT `FK_PRODUCT_REVIEW_TO_PRODUCT_REVIEW_IMAGE_2` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `PRODUCT_REVIEW` (
	`MEMBER_ID`
);

ALTER TABLE `BASKET_ITEM` ADD CONSTRAINT `FK_PRODUCT_TO_BASKET_ITEM_1` FOREIGN KEY (
	`P_ID`
)
REFERENCES `PRODUCT` (
	`P_ID`
);

ALTER TABLE `BASKET_ITEM` ADD CONSTRAINT `FK_MEMBER_TO_BASKET_ITEM_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `NT_PLATING_LIKE` ADD CONSTRAINT `FK_MEMBER_TO_NT_PLATING_LIKE_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `NT_PLATING_LIKE` ADD CONSTRAINT `FK_NT_PLATING_CONTENT_TO_NT_PLATING_LIKE_1` FOREIGN KEY (
	`B_NO`
)
REFERENCES `NT_PLATING_CONTENT` (
	`B_NO`
);

ALTER TABLE `NT_RECIPE_LIKE` ADD CONSTRAINT `FK_MEMBER_TO_NT_RECIPE_LIKE_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `NT_RECIPE_LIKE` ADD CONSTRAINT `FK_NT_RECIPE_CONTENT_TO_NT_RECIPE_LIKE_1` FOREIGN KEY (
	`B_NO`
)
REFERENCES `NT_RECIPE_CONTENT` (
	`B_NO`
);

ALTER TABLE `CR_RECIPE_CONTENT_IMAGE` ADD CONSTRAINT `FK_CR_RECIPE_CONTENT_TO_CR_RECIPE_CONTENT_IMAGE_1` FOREIGN KEY (
	`CRRECONTENT_NO`
)
REFERENCES `CR_RECIPE_CONTENT` (
	`CRRECONTENT_NO`
);

ALTER TABLE `MBTI` ADD CONSTRAINT `FK_MEMBER_TO_MBTI_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `DELIVERY` ADD CONSTRAINT `FK_ORDER_TO_DELIVERY_1` FOREIGN KEY (
	`ORDER_NUMBER`
)
REFERENCES `ORDER` (
	`ORDER_NUMBER`
);

ALTER TABLE `CopyOfPAYMENT` ADD CONSTRAINT `FK_ORDER_TO_CopyOfPAYMENT_1` FOREIGN KEY (
	`ORDER_NUMBER`
)
REFERENCES `ORDER` (
	`ORDER_NUMBER`
);

ALTER TABLE `AGREEMENT_HISTORY` ADD CONSTRAINT `FK_MEMBER_TO_AGREEMENT_HISTORY_1` FOREIGN KEY (
	`MEMBER_ID`
)
REFERENCES `MEMBER` (
	`MEMBER_ID`
);

ALTER TABLE `AGREEMENT_HISTORY` ADD CONSTRAINT `FK_MEMBERAGREEMENT_TO_AGREEMENT_HISTORY_1` FOREIGN KEY (
	`MA_ID`
)
REFERENCES `MEMBERAGREEMENT` (
	`MA_ID`
);

