CREATE TABLE "MEMBER" (
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMBER_PASSWORD"	VARCHAR2(20)		NOT NULL,
	"MEMBER_NAME"	VARCHAR2(20)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PHONE"	VARCHAR2(20)		NOT NULL,
	"MEMBER_ADDRESS"	VARCHAR2(200)		NOT NULL,
	"MEMBER_GENDER"	CHAR(1)		NOT NULL,
	"MEMBER_BIRTHOFDATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '67자 미만';

COMMENT ON COLUMN "MEMBER"."MEMBER_GENDER" IS '"M", "F"';

CREATE TABLE "NTPC" (
	"PB_NO"	NUMBER		NOT NULL,
	"PB_CONCEPT"	NUMBER		NOT NULL,
	"PB_TITLE"	VARCHAR2(60)		NOT NULL,
	"PB_CONTENT"	VARCHAR2(900)		NOT NULL,
	"PB_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "NTPC"."PB_CONCEPT" IS '1.생일 2.캠핑 3. 홈파티 4.안주';

COMMENT ON COLUMN "NTPC"."PB_TITLE" IS '20자미만';

COMMENT ON COLUMN "NTPC"."PB_CONTENT" IS '300자미만';

CREATE TABLE "NTPR" (
	"PR_NO"	NUMBER		NOT NULL,
	"PR_CONTENT"	VARCHAR2(300)		NOT NULL,
	"PR_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"PB_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "NTPR"."PR_CONTENT" IS '100자미만';

CREATE TABLE "NTRC" (
	"RB_NO"	NUMBER		NOT NULL,
	"RB_CONCEPT"	NUMBER		NOT NULL,
	"RB_TITLE"	VARCHAR2(60)		NOT NULL,
	"RB_CONTENT"	VARCHAR2(900)		NOT NULL,
	"RB_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "NTRC"."RB_CONCEPT" IS '1.한식 2.중식 3.일식 4.양식';

COMMENT ON COLUMN "NTRC"."RB_TITLE" IS '20자미만';

COMMENT ON COLUMN "NTRC"."RB_CONTENT" IS '300자미만';

CREATE TABLE "NTRI" (
	"RI_NO"	NUMBER		NOT NULL,
	"RI_FILE"	VARCHAR2(300)		NOT NULL,
	"RB_NO"	NUMBER		NOT NULL
);

CREATE TABLE "NTRR" (
	"RR_NO"	NUMBER		NOT NULL,
	"RR_CONTENT"	VARCHAR2(300)		NOT NULL,
	"RR_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"RB_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "NTRR"."RR_CONTENT" IS '100자미만';

CREATE TABLE "NTCC" (
	"CB_NO"	NUMBER		NOT NULL,
	"CB_TITLE"	VARCHAR2(60)		NOT NULL,
	"CB_CONTENT"	VARCHAR2(900)		NOT NULL,
	"CB_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "NTCC"."CB_TITLE" IS '20자미만';

COMMENT ON COLUMN "NTCC"."CB_CONTENT" IS '300자미만';

CREATE TABLE "NTCI" (
	"CI_NO"	NUMBER		NOT NULL,
	"CI_FILE"	VARCHAR2(300)		NOT NULL,
	"CB_NO"	NUMBER		NOT NULL
);

CREATE TABLE "NTCR" (
	"CR_NO"	NUMBER		NOT NULL,
	"CR_CONTENT"	VARCHAR2(300)		NOT NULL,
	"CR_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"CB_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "NTCR"."CR_CONTENT" IS '100자미만';

CREATE TABLE "NTCL" (
	"CB_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "NTPI" (
	"PI_NO"	NUMBER		NOT NULL,
	"PI_FILE"	VARCHAR2(300)		NOT NULL,
	"PB_NO"	NUMBER		NOT NULL
);

CREATE TABLE "NTPL" (
	"PB_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "NTRL" (
	"RB_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL
);



ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBERID_MEMBER" PRIMARY KEY (
	"MEMBER_ID"
);

ALTER TABLE "NTPC" ADD CONSTRAINT "PK_PBNO_NTPC" PRIMARY KEY (
	"PB_NO"
);

ALTER TABLE "NTPR" ADD CONSTRAINT "PK_PRNO_NTPR" PRIMARY KEY (
	"PR_NO"
);

ALTER TABLE "NTRC" ADD CONSTRAINT "PK_RBNO_NTRC" PRIMARY KEY (
	"RB_NO"
);

ALTER TABLE "NTRI" ADD CONSTRAINT "PK_RINO_NTRI" PRIMARY KEY (
	"RI_NO"
);

ALTER TABLE "NTRR" ADD CONSTRAINT "PK_RRNO_NTRR" PRIMARY KEY (
	"RR_NO"
);

ALTER TABLE "NTCC" ADD CONSTRAINT "PK_CBNO_NTCC" PRIMARY KEY (
	"CB_NO"
);

ALTER TABLE "NTCI" ADD CONSTRAINT "PK_CINO_NTCI" PRIMARY KEY (
	"CI_NO"
);

ALTER TABLE "NTCR" ADD CONSTRAINT "PK_CRNO_NTCR" PRIMARY KEY (
	"CR_NO"
);

ALTER TABLE "NTCL" ADD CONSTRAINT "PK_CBNO_ID_NTCL" PRIMARY KEY (
	"CB_NO",
	"MEMBER_ID"
);

ALTER TABLE "NTPI" ADD CONSTRAINT "PK_PINO_NTPI" PRIMARY KEY (
	"PI_NO"
);

ALTER TABLE "NTPL" ADD CONSTRAINT "PK_PBNO_ID_NTPL" PRIMARY KEY (
	"PB_NO",
	"MEMBER_ID"
);

ALTER TABLE "NTRL" ADD CONSTRAINT "PK_RBNO_ID_NTRL" PRIMARY KEY (
	"RB_NO",
	"MEMBER_ID"
);





ALTER TABLE "NTPC" ADD CONSTRAINT "FK_ID_NTPC_MEMBER" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "NTPR" ADD CONSTRAINT "FK_PBNO_NTPR_NTPC" FOREIGN KEY (
	"PB_NO"
)
REFERENCES "NTPC" (
	"PB_NO"
);

ALTER TABLE "NTPR" ADD CONSTRAINT "FK_ID_NTPR_MEMBER" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "NTRC" ADD CONSTRAINT "FK_ID_NTRC_MEMBER" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "NTRI" ADD CONSTRAINT "FK_RBNO_NTRI_NTRC" FOREIGN KEY (
	"RB_NO"
)
REFERENCES "NTRC" (
	"RB_NO"
);

ALTER TABLE "NTRR" ADD CONSTRAINT "FK_RBNO_NTRR_NTRC" FOREIGN KEY (
	"RB_NO"
)
REFERENCES "NTRC" (
	"RB_NO"
);

ALTER TABLE "NTRR" ADD CONSTRAINT "FK_ID_NTRR_MEMBER" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "NTCC" ADD CONSTRAINT "FK_ID_NTCC_MEMBER" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "NTCI" ADD CONSTRAINT "FK_CBNO_NTCI_NTCC" FOREIGN KEY (
	"CB_NO"
)
REFERENCES "NTCC" (
	"CB_NO"
);

ALTER TABLE "NTCR" ADD CONSTRAINT "FK_CBNO_NTCR_NTCC" FOREIGN KEY (
	"CB_NO"
)
REFERENCES "NTCC" (
	"CB_NO"
);

ALTER TABLE "NTCR" ADD CONSTRAINT "FK_ID_NTCR_MEMBER" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "NTCL" ADD CONSTRAINT "FK_CBNO_NTCL_NTCC" FOREIGN KEY (
	"CB_NO"
)
REFERENCES "NTCC" (
	"CB_NO"
);

ALTER TABLE "NTCL" ADD CONSTRAINT "FK_ID_NTCL_MEMBER" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "NTPI" ADD CONSTRAINT "FK_PBNO_NTPI_NTPC" FOREIGN KEY (
	"PB_NO"
)
REFERENCES "NTPC" (
	"PB_NO"
);

ALTER TABLE "NTPL" ADD CONSTRAINT "FK_PBNO_NTPL_NTPC" FOREIGN KEY (
	"PB_NO"
)
REFERENCES "NTPC" (
	"PB_NO"
);

ALTER TABLE "NTPL" ADD CONSTRAINT "FK_ID_NTPL_MEMBER" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "NTRL" ADD CONSTRAINT "FK_RBNO_NTRL_NTRC" FOREIGN KEY (
	"RB_NO"
)
REFERENCES "NTRC" (
	"RB_NO"
);

ALTER TABLE "NTRL" ADD CONSTRAINT "FK_ID_NTRL_MEMBER" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);