CREATE TABLE MEMBER(
	MEMBER_ID	VARCHAR2(20)	NOT NULL,
	MEMBER_PASSWORD	VARCHAR2(20)	NOT NULL,
	MEMBER_NAME	VARCHAR2(20)	NOT NULL,
	MEMBER_EMAIL	VARCHAR2(50)	NOT NULL,
	MEMBER_PHONE	VARCHAR2(20)	NOT NULL,
	MEMBER_ADDRESS	VARCHAR2(200)	NOT NULL,
	MEMBER_GENDER	CHAR(1)	NOT NULL,
	MEMBER_BIRTHOFDATE	DATE	NOT NULL
);
COMMENT ON COLUMN MEMBER.MEMBER_ADDRESS IS '67자 미만';
COMMENT ON COLUMN MEMBER.MEMBER_GENDER IS '"M", "F"';

CREATE TABLE PRODUCT (
	P_ID	VARCHAR2(20)	NOT NULL,
	P_NAME	VARCHAR2(100)	NOT NULL,
	P_CATEGORY	NUMBER	NOT NULL,
	P_PRICE	NUMBER	NOT NULL,
	P_SELLAMOUNT	NUMBER	NOT NULL,
	P_WEIGHT	NUMBER	NULL,
	P_CALORIE	NUMBER	NULL,
	P_FLAVOR	VARCHAR2(20)	NULL,
	P_POSTDATE	TIMESTAMP	NOT NULL,
	P_SALECHECK	CHAR(1)	NOT NULL,
	P_DETAIL	VARCHAR2(900)	NOT NULL
);
COMMENT ON COLUMN PRODUCT.P_NAME IS '34자 미만';
COMMENT ON COLUMN PRODUCT.P_CATEGORY IS '1. 한식, 2.중식, 3.일식, 4.양식, 5.동남아, 6.기타';
COMMENT ON COLUMN PRODUCT.P_SALECHECK IS '"Y", "N"';

CREATE TABLE ORDER_ORDER(
	ORDER_NUMBER	VARCHAR2(20)	NOT NULL,
	ORDER_CONTACT	NUMBER	NOT NULL,
	ORDER_REQUEST	VARCHAR2(150)	NOT NULL,
	ORDER_DATE	TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
	ORDER_STATUS	VARCHAR2(30)	NULL,
	ORDER_PAYMENT	VARCHAR2(30)	NOT NULL,
	MEMBER_ID	VARCHAR2(20)	NOT NULL,
	ORDER_DELIVERY	VARCHAR2(100)	NOT NULL
);
COMMENT ON COLUMN ORDER_ORDER.ORDER_REQUEST IS '51자 미만';

CREATE TABLE PRODUCT_REVIEW (
	PRODUCTREVIEW_NO	NUMBER	NOT NULL,
	MEMBER_ID	VARCHAR2(20)	NOT NULL,
	PRODUCTREVIEW_POSTDATE	TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
	PRODUCTREVIEW_CONTENT	VARCHAR2(300)	NOT NULL
);
COMMENT ON COLUMN PRODUCT_REVIEW.PRODUCTREVIEW_CONTENT IS '100자 미만';

CREATE TABLE PRODUCT_REVIEW_IMAGE (
	PRODUCTREVIEW_IMAGENO	NUMBER	NOT NULL,
	PRODUCTREVIEW_NO	NUMBER	NOT NULL,
	MEMBER_ID	VARCHAR2(20)	NOT NULL,
	PRODUCTREVIEW_IMAGEPOSITION	VARCHAR2(300)	NOT NULL
);

CREATE TABLE BASKET_ITEM (
	P_ID	VARCHAR2(20)	NOT NULL,
	MEMBER_ID	VARCHAR2(20)	NOT NULL,
	BASKETITEM_AMOUNT	NUMBER	NOT NULL
);

CREATE TABLE ORDERED_PRODUCT (
	P_ID	VARCHAR2(20)	NOT NULL,
	ORDER_NUMBER	VARCHAR2(20)	NOT NULL,
	ORDEREDPRODUCT_AMOUNT	NUMBER	NOT NULL
);

CREATE TABLE DELIVERY (
	ORDER_NUMBER	VARCHAR2(20)	NOT NULL,
	D_DATE	DATE	NOT NULL,
	D_COMPANY	VARCHAR2(100)	NOT NULL,
	D_NUMBER	NUMBER	NOT NULL,
	D_STATUS	CHAR(3)	NOT NULL,
	D_TYPE	VARCHAR2(50)	NOT NULL
);
COMMENT ON COLUMN DELIVERY.D_STATUS IS '1 - 발송, 2 - 배송 중, 3- 배송 완료';

CREATE TABLE PAYMENT (
	PAY_NUMBER	NUMBER	NOT NULL,
	ORDER_NUMBER	VARCHAR2(20)	NOT NULL,
	APY_NAME	VARCHAR2(50)	NOT NULL,
	PAY_DATE	TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
	PAY_TOTAL	NUMBER	NOT NULL,
	PAY_METHOD	NUMBER	NOT NULL,
	MEMBER_ID	VARCHAR2(20)	NOT NULL
);
COMMENT ON COLUMN PAYMENT.PAY_METHOD IS '1. 카드 2. 무통장입금 3. 실시간계좌이체';

CREATE TABLE DETAIL_IMAGE (
	P_ID	VARCHAR2(20)	NOT NULL,
	D_FILE	VARCHAR2(300)	NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	MEMBER_ID
);

ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (
	P_ID
);

ALTER TABLE ORDER_ORDER ADD CONSTRAINT PK_ORDER PRIMARY KEY (
	ORDER_NUMBER
);

ALTER TABLE PRODUCT_REVIEW ADD CONSTRAINT PK_PRODUCT_REVIEW PRIMARY KEY (
	PRODUCTREVIEW_NO
);

ALTER TABLE PRODUCT_REVIEW_IMAGE ADD CONSTRAINT PK_PRODUCT_REVIEW_IMAGE PRIMARY KEY (
	PRODUCTREVIEW_IMAGENO
);

ALTER TABLE BASKET_ITEM ADD CONSTRAINT PK_BASKET_ITEM PRIMARY KEY (
	P_ID,
	MEMBER_ID
);

ALTER TABLE DELIVERY ADD CONSTRAINT PK_DELIVERY PRIMARY KEY (
	ORDER_NUMBER
);

ALTER TABLE PAYMENT ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (
	PAY_NUMBER,
	ORDER_NUMBER
);

ALTER TABLE ORDER_ORDER ADD CONSTRAINT FK_MEMBER_TO_ORDER FOREIGN KEY (
	MEMBER_ID
)
REFERENCES MEMBER (
	MEMBER_ID
);

ALTER TABLE PRODUCT_REVIEW ADD CONSTRAINT FK_MEMBER_TO_PRODUCT_REVIEW FOREIGN KEY (
	MEMBER_ID
)
REFERENCES MEMBER (
	MEMBER_ID
);

ALTER TABLE PRODUCT_REVIEW_IMAGE ADD CONSTRAINT FK_PR_RE_PR_RE_IMAGE FOREIGN KEY (
	PRODUCTREVIEW_NO
)
REFERENCES PRODUCT_REVIEW (
	PRODUCTREVIEW_NO
);

ALTER TABLE BASKET_ITEM ADD CONSTRAINT FK_PRODUCT_TO_BASKET_ITEM FOREIGN KEY (
	P_ID
)
REFERENCES PRODUCT (
	P_ID
);

ALTER TABLE BASKET_ITEM ADD CONSTRAINT FK_MEMBER_TO_BASKET_ITEM FOREIGN KEY (
	MEMBER_ID
)
REFERENCES MEMBER (
	MEMBER_ID
);

ALTER TABLE ORDERED_PRODUCT ADD CONSTRAINT FK_PRO_OR_PRODUCT FOREIGN KEY (
	P_ID
)
REFERENCES PRODUCT (
	P_ID
);

ALTER TABLE ORDERED_PRODUCT ADD CONSTRAINT FK_ORDER_TO_ORDERED_PRODUCT FOREIGN KEY (
	ORDER_NUMBER
)
REFERENCES ORDER_ORDER (
	ORDER_NUMBER
);

ALTER TABLE DELIVERY ADD CONSTRAINT FK_ORDER_TO_DELIVERY FOREIGN KEY (
	ORDER_NUMBER
)
REFERENCES ORDER_ORDER (
	ORDER_NUMBER
);

ALTER TABLE PAYMENT ADD CONSTRAINT FK_ORDER_TO_PAYMENT FOREIGN KEY (
	ORDER_NUMBER
)
REFERENCES ORDER_ORDER (
	ORDER_NUMBER
);

ALTER TABLE PAYMENT ADD CONSTRAINT FK_MEMBER_TO_PAYMENT FOREIGN KEY (
	MEMBER_ID
)
REFERENCES MEMBER (
	MEMBER_ID
);

ALTER TABLE DETAIL_IMAGE ADD CONSTRAINT FK_PRODUCT_TO_DETAIL_IMAGE FOREIGN KEY (
	P_ID
)
REFERENCES PRODUCT (
	P_ID
);

