package kh.semi.bobn.mypage.model.vo;

public class MypageVo {
	
	//member table
//	MEMBER_ID          NOT NULL VARCHAR2(20) 
//	MEMBER_PASSWORD    NOT NULL VARCHAR2(20) 
//	MEMBER_NAME        NOT NULL VARCHAR2(20) 
//	MEMBER_EMAIL       NOT NULL VARCHAR2(50) 
//	MEMBER_PHONE       NOT NULL VARCHAR2(20) 
//	MEMBER_GENDER      NOT NULL CHAR(1)      
//	MEMBER_BIRTHOFDATE NOT NULL DATE   
	
	//qna table
//	QNA_NO       NOT NULL NUMBER         
//	QNA_POSTDATE NOT NULL TIMESTAMP(6)   
//	QNA_TITLE    NOT NULL VARCHAR2(300)  
//	QNA_CONTENT  NOT NULL VARCHAR2(3900) 
//	MEMBER_ID    NOT NULL VARCHAR2(20)   

	//qna recomment table
//	QNARECOMMENT_NO       NOT NULL NUMBER         
//	QNARECOMMENT_POSTDATE NOT NULL TIMESTAMP(6)   
//	QNARECOMMENT_CONTENT  NOT NULL VARCHAR2(3900) 
//	QNA_NO                NOT NULL NUMBER    


}
